title: "A simple blockquote component"
# preview: "@preview-component"
status: wip

variants:
  - name: default
    context:
      text: "Blockquotes are cool"
      citation: "Objectively docs"
  - name: fancy
    context:
      text: "Blockquotes are fancy!"
      # citation: "Objectively docs"
      author: "Objectively"
