title: "Fonts"
preview: "@preview-component"
status: ready
context:
  typefaces:
    - id: sans
      name: Montserrat
      description: |
        <p>The old posters and signs in the traditional Montserrat neighborhood of Buenos Aires inspired Julieta Ulanovsky to design this typeface and rescue the beauty of urban typography that emerged in the first half of the twentieth century. As urban development changes that place, it will never return to its original form and loses forever the designs that are so special and unique. The letters that inspired this project have work, dedication, care, color, contrast, light and life, day and night! These are the types that make the city look so beautiful. The Montserrat Project began with the idea to rescue what is in Montserrat and set it free under a libre license, the SIL Open Font License.</p>

    - id: serif
      name: Crimson Text
      description: |
        <p>Crimson Text is a font family for book production in the tradition of beautiful oldstyle typefaces.</p>

    - id: material-icons
      name: Material Icons
      description: |
        <p>We use Google's <a href="https://material.io/icons/" target="_blank">Material Icons</a> as our base icon set.</p>

    - id: fa
      name: Font Awesome
      description: |
        <p>We use <a href="http://fontawesome.io/" target="_blank">Font Awesome</a> as our secondary icon set. We primarily use it for social media icons.</p>